# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: 1059Studio.FFmpegFreeUI
PackageVersion: 0.5.0.0
InstallerType: portable
Commands:
- ffmpegfreeui
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Lake1059/FFmpegFreeUI/releases/download/0.5/FFmpegFreeUI.x86.exe
  InstallerSha256: A5F3B3087367ABE523C40529871AD351F909086F91AB3F6837CEF85DE059A872
- Architecture: x64
  InstallerUrl: https://github.com/Lake1059/FFmpegFreeUI/releases/download/0.5/FFmpegFreeUI.x64.exe
  InstallerSha256: 98123C97477F4D7DF3D233BCBE3B8529F8A9AD2A7F2A57128C8F86B822810958
- Architecture: arm64
  InstallerUrl: https://github.com/Lake1059/FFmpegFreeUI/releases/download/0.5/FFmpegFreeUI.arm64.exe
  InstallerSha256: 5E7BD968DBCDDAF00074C929AECC14699C1A9C74D823E21A0EE5CC40144F489C
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-06-02
